name: example
description: Example app for tinode_flutter_chat.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5
  tinode_flutter_chat:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 10.1.0

flutter:
  uses-material-design: true
